apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  creationTimestamp: "2020-12-10T23:37:32Z"
  generation: 1
  name: default
  namespace: argocd
  resourceVersion: "48149"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/appprojects/default
  uid: bda95a58-6b67-4ec7-909f-dd7edeb3547f
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
status: {}
