apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  creationTimestamp: "2020-12-10T23:37:01Z"
  generation: 1
  name: argocd
  namespace: argocd
  resourceVersion: "48248"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argocd/argocds/argocd
  uid: 6dc7a5bc-1b9d-4631-922e-09ec68063693
spec:
  applicationInstanceLabelKey: argo-app
  dex:
    openShiftOAuth: true
  grafana:
    enabled: true
    ingress:
      enabled: false
    route:
      enabled: true
  kustomizeBuildOptions: --load_restrictor none
  prometheus:
    enabled: true
    route:
      enabled: true
    size: 1
  server:
    insecure: false
    route:
      enabled: true
status:
  applicationController: Running
  dex: Running
  phase: Available
  redis: Running
  repo: Running
  server: Running
