apiVersion: apps/v1
kind: Deployment
metadata:
  name: exceptions
  namespace: exceptions
spec:
  selector:
    matchLabels:
      app: hello-openshift
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-openshift
    spec:
      containers:
        - name: hello-openshift
          image: #image
          ports:
            - containerPort: 8080